services:
  db:
    image: postgres:16
    container_name: adventorator-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    # Default to .env.docker (created from .env.docker.example). Allow override via COMPOSE_ENV_FILE.
    env_file: .env.docker
    # This environment block overrides variables from the env file
    # specifically for this container.
    environment:
      # Tell the app to connect to the 'db' service hostname instead of 'localhost'.
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LLM_API_URL=${LLM_API_URL:-http://ollama:11434}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-18000}:18000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:18000/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data:
