services:
  db:
    image: postgres:16
    container_name: adventorator-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
    ports:
      - target: 5432
        published: ${DB_PORT:-5432}
        protocol: tcp
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    env_file: .env
    # This environment block overrides variables from the .env file
    # specifically for this container.
    environment:
      # Tell the app to connect to the 'db' service hostname instead of 'localhost'.
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Tell the app to send webhooks back to the host machine, where web_cli.py's sink will be listening.
      # The port must match the SINK_PORT in web_cli.py (default 19000).
      - DISCORD_WEBHOOK_URL_OVERRIDE=http://host.docker.internal:19000
      - LLM_API_URL=http://host.docker.internal:11434
    depends_on:
      db:
        condition: service_healthy
    ports:
      - target: 18000
        published: ${APP_PORT:-18000}
        protocol: tcp
        mode: host

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data:
