name: "Feature Epic"
description: "Production-ready feature composed of multiple Stories."
title: "[Epic] <Feature name>"
labels: ["type: epic"]
assignees: []
about: "A production-ready feature composed of multiple stories. Anchors architecture, ADRs, and traceability. Lives across multiple sprints if needed."
---

## Summary
One or two sentences describing the feature.  
Example: *Deliver X so that Y can Z.*

## Architecture Overview (C4/ADRs)
- C4 Context: <link>  
- C4 Container: <link>  
- C4 Component: <link>  
- ADRs: ADR-001, ADR-002  

## Architecture Conformance & Traceability
Explain how this Epic aligns with ADRs and architecture.  
Example: *Touches ADR-003 and ADR-004; aligns with Component A and Service B.*

## Objectives & Success Criteria
- Business goal(s)  
- Technical goal(s)  
- SLOs/SLAs (latency, availability, cost, safety)  
- Risk considerations  

## Risks & Mitigations (risk-first)
- Risk: schema break → **Mitigation**: contract tests + deprecation window  
- Rollback: disable feature flag `feature.foo`  

## Stories (to be created/linked)
- [ ] #<StoryID-or-placeholder> — <title>  
- [ ] #<StoryID-or-placeholder> — <title>  
- [ ] #<StoryID-or-placeholder> — <title>  

## Definition of Done (Epic)
- [ ] All Stories merged behind a feature flag with rollback plan  
- [ ] Tests pass at all levels (unit, integration, contract, perf, security; AI eval if applicable)  
- [ ] SLOs validated (no regression vs. budget)  
- [ ] Observability (metrics/logs/traces) and alerts/dashboards in place  
- [ ] Docs & runbooks updated; ADRs added/updated as needed  
