---
name: "Task"
description: "Per-prompt unit of work or small developer action supporting a Story."
title: "[Task] <Actionable verb + object>"
labels: ["type: task"]
assignees: []
about: "A per-prompt unit of work. Represents one or a few changes or tool runs that move a Story forward. Multiple Tasks roll into a Story."
---

## Objective
What this Task achieves toward the Story.

Story Link: #<StoryID>

## Steps (as applicable)
- [ ] Update/define contracts (OpenAPI/Proto/GraphQL SDL)
- [ ] Write acceptance tests (ATDD/BDD) and unit/property tests
- [ ] Implement code changes against tests
- [ ] Add/adjust metrics, logs, traces
- [ ] Update documentation/runbook

## Outputs
PR/commit links, generated files, test artifacts.

- PR: #1234  
- File: openapi/foo.yaml  
- Tests: tests/foo_spec.py  

## Traceability
Map to Story acceptance criteria and any ADRs touched.  
Example: `Supports AC-2 and AC-3; references ADR-005`

## Definition of Done (DoD)
- [ ] Tests written and passing locally/CI
- [ ] Changes linked to Story; references ADRs if applicable
- [ ] Code reviewed/approved or attached to PR
