name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-postgres-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env for compose
        run: |
          cat > .env << 'EOF'
          POSTGRES_USER=adventorator
          POSTGRES_PASSWORD=adventorator
          POSTGRES_DB=adventorator
          APP_PORT=18000
          # LLM not needed for tests; point to a placeholder
          LLM_API_URL=http://localhost:11434
          EOF

      - name: Build and start Postgres
        run: |
          docker compose up -d db
          docker compose ps

      - name: Wait for DB healthy
        run: |
          for i in {1..30}; do
            if docker compose ps db | grep -q "healthy"; then echo "DB is healthy"; break; fi
            sleep 2
          done
          docker compose ps

      - name: Run migrations and tests in app container
        run: |
          # Build image and run ephemeral app container for tests
          docker compose run --rm app sh -lc 'PYTHONPATH=./src alembic upgrade head && pytest -q'

      - name: Tear down
        if: always()
        run: docker compose down -v
