name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Ruff Lint
        run: ruff check src tests

      - name: Mypy Type Check
        run: mypy src

      - name: Run tests
        env:
          ENV: dev
          DISCORD_PUBLIC_KEY: dummy
          DATABASE_URL: sqlite+aiosqlite:///./adventurator_test.sqlite3
        run: |
          pytest -q
